Always allow to change group leader
This is what you're getting back if you want to change the group leader
for a group with a subscription:

{
  success: false,
  error: "NotAuthorized",
  message:
    "You can not change the leader while the group has an active plan."
}

So let's actually just remove that check, because we have free
subscriptions for everybody so it really doesn't matter who's the
leader.

Signed-off-by: aszlig <aszlig@nix.build>